### ISSUE TITLE
iPadなどで閲覧できない事があるらしい

### ISSUE THREAD

**Issue by HaiTo** [moneyforward/tax_newurl#33]
アプリ内のWebViewなどで開かれるともしかするともしかして動かないのかも？
あるいはOffline？ 
とはいえわからないので、そういった事象が存在するらしいという情報だけ。

**Comment by hkdnet** [comment]
というかスマホで見れるようなデザインにしないと厳しいのかもですねえ

**Comment by Fukahori** [comment]
国税庁のサイトは検索 => コンテンツを読むことが目的なので、基本的にはPC利用（画面幅がある程度ある前提）でいいと思います。スマホで見ることはあまりない。
想定利用者：会計事務所、経理部（内勤）
